version: "3.9"

services:

  postgres:
    image: postgres:17

    container_name: geovia-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: geovia
      POSTGRES_USER: geovia
      POSTGRES_PASSWORD: geovia

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: